"""Adicionar campo telefone ao usuario

Revision ID: 70f5a4f6c49e
Revises: f810682d02dd
Create Date: 2026-02-05 09:25:40.835535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f5a4f6c49e'
down_revision = 'f810682d02dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
